# config.yaml

model_transformers:
  turned_on: False
  name: "Qwen/Qwen3-1.7B"
  max_new_tokens: 5000
  quantisation: 4bit
  batch_status: True
  batch_size: 2

model_bedrock:
  turned_on: True
  profile_name: YOUR_PROFILE_NAME
  region_for_profile: YOUR_AWS_REGION
  name: LLM_NAME

dataset:
  name: "cais/mmlu"
  number_examples: 100
  number_subjects: 1

paths:
  results: "./results/result_" 
  logs: "./logs/log_"